name: Docker Build

on:
  pull_request:
  push:
    branches:
      - "main"
    tags:
      - "*"

jobs:
  docker-build:
    if: >
      startsWith(github.ref, 'refs/tags/v') }} ||
      (
        github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        && !startsWith(github.event.head_commit.message, 'bump:')
      )

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "ghcr.io/${{ github.repository }}"
          tags: |
            type=ref,event=pr
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{version}}
            type=raw,value=edge,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) || startsWith(github.ref, 'refs/tags/v') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64/v8
          cache-to: |
            type=inline
            type=registry,ref=ghcr.io/${{ github.repository }}/buildcache:${{ github.ref_name }},mode=max
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository }}/buildcache:${{ github.ref_name }}
            type=registry,ref=ghcr.io/${{ github.repository }}/buildcache:edge
            type=registry,ref=ghcr.io/${{ github.repository }}/buildcache:latest
            type=registry,ref=ghcr.io/${{ github.repository }}:edge
            type=registry,ref=ghcr.io/${{ github.repository }}:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
