name: PyPI Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          cache: 'poetry'
          python-version: "3.12"

      - name: Build package
        run: poetry build -vvv

      - run: ls dist/*

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
